### PR TITLE
Another initial commit which contains library itself.

### PR DESCRIPTION
**Pull request by RHEmployee**

### CODE REVIEW

**Comment by RHEmployee** [comment]
Whould you please take a look if proposed changes are sane? Thank you :)

**Comment by hegerj** [comment]
LGTM, shall I merge it?

**Comment by psss** [comment]
Hint: You might also want to `pod2markdown lib.sh > ../README.md` so that the library docs are easily accessible to the users.

**Comment by RHEmployee** [comment]
> Hint: You might also want to `pod2markdown lib.sh > ../README.md` so that the library docs are easily accessible to the users.

So please, don't make this as optional step in documentation if this step is enforced later in pull request.
From docs:
Optionally generate documentation to readme (pod2markdown lib.sh > ../README.md)

which seems to be wrong if you need to force it in PR.

**Comment by RHEmployee** [comment]
Added in new commit.

**Comment by RHEmployee** [comment]
Just ping :). Documentation has been added

**Comment by sopos** [comment]
@RHEmployee, you are the owner of this repo, you do not need to ask for permission unless you really want to. You have full rights over this repo so you can do virtually anything you want to. There are just some hints and recommendations to keep some basic culture.
Drive it as you would like to drive any other public project of yours. Set up workflow which suits you well to keep high quality and reliability of the library.

**Comment by RHEmployee** [comment]
Hi. Thank you. I maybe expected some basic review (already done by Petr, thanks!) from more skilled people, because this is first time what I opensource beaker library.
Ok. Then merging and done.
Thanks.

**Pull request merged**
